name: build release
on:
  push:
    tags:
      - '**'
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
    - name: Write release version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 22
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build
      run: ./gradlew -Pversion=${VERSION} build sourcesJar javadocJar publishToSonatype closeAndReleaseSonatypeStagingRepository
      env:
        ORG_GRADLE_PROJECT_githubActor: ${{ secrets.GITHUBACTOR }}
        ORG_GRADLE_PROJECT_githubToken: ${{ secrets.GITHUBTOKEN }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        ORG_GRADLE_PROJECT_sonatypeUser: ${{ secrets.SONATYPE_USER }}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
