name: Publish SNAPSHOT version to GitHub Packages
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          java-version: 21
      - name: Publish package
        run: gradle publish
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUBACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
